sonar.projectKey=teilorbarcelos_backend-go
sonar.projectName=Backend Go
sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,docs/**,scratch/**,tmp/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
