{
 "title": "Go Backend Metrics",
 "tags": [ "golang" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total de Requisições (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (method, path)"
    }
   ]
  },
  {
   "title": "Latência Média (Segundos)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "Requisições por Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(http_requests_total) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Uso de Memória",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "RSS" },
    { "expr": "process_virtual_memory_bytes", "legendFormat": "Memória Virtual" },
    { "expr": "go_memstats_heap_alloc_bytes", "legendFormat": "Heap Alloc" }
   ]
  },
  {
   "title": "Uso de CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "Total CPU Usage"
    }
   ]
  },
  {
   "title": "File Descriptors (FDs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "process_open_fds", "legendFormat": "Abertos" },
    { "expr": "process_max_fds", "legendFormat": "Máximo" }
   ]
  },
  {
   "title": "Threads/Goroutines Ativas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "go_threads", "legendFormat": "Threads do Go" },
    { "expr": "go_goroutines", "legendFormat": "Goroutines Ativas" }
   ]
  },
  {
   "title": "Taxa de Erros HTTP (Por Minuto)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"5..\"}[1m])) * 60",
     "legendFormat": "Erro 5xx"
    },
    {
     "expr": "sum(rate(http_requests_total{status=~\"4..\"}[1m])) * 60",
     "legendFormat": "Erro 4xx"
    }
   ]
  }
 ]
}